SRC_FILE    = \
        matrices.F \
	    problem.F \
        celem.F90 \
            dirichlet.F90 \
            elem.F \
	    exact.F90 \
	    fake.F90 \
	    finalize.F90 \
	    getf.F90 \
            initialize.F90 \
            main.F90 \
            set_initial_mesh.F90 \
	    set_mesh_refinement.F90 \
	    soldis.F90 \
            my_own_tests.F \
            compute_BC_interp_error.F









